package accessingdatamysql.controllers;

import com.example.accessingdatamysql.dao.entities.Factory;
import com.example.accessingdatamysql.dao.entities.Workshop;
import com.example.accessingdatamysql.dao.repo.WorkshopRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class WorkshopController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private WorkshopRepository workshopRepository;

    @PostMapping(path="/workshop") // Map ONLY POST Requests
    public @ResponseBody String addNewWorkshop (@RequestParam Integer factoryID) {
        Factory factory = new Factory();
        Workshop w1 = new Workshop(factory);
        Workshop w2 = new Workshop(factory);
        Workshop w3 = new Workshop(factory);
        workshopRepository.save(w1);
        workshopRepository.save(w2);
        workshopRepository.save(w3);
        return "Saved";
    }
}