package com.example.accessingdatamysql.controllers;

import com.example.accessingdatamysql.dao.repo.PersonalRepository;
import com.example.accessingdatamysql.dto.PersonalCategoryDTO;
import com.example.accessingdatamysql.dto.PersonalDTO;
import com.example.accessingdatamysql.dto.PersonalFunctionDTO;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TableView;
import net.rgielen.fxweaver.core.FxmlView;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Component
@FxmlView("Personal.fxml")

public class PersonalController {
    @FXML
    private Button add;
    @FXML private Button edit;
    @FXML private Button drop;
    @FXML private TableView<PersonalCategoryDTO> personalCategoriesTable;
    @FXML private TableView<PersonalFunctionDTO> personalFunctionsTable;
    @FXML private TableView<PersonalDTO> personalTable;
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PersonalRepository personalRepository;

    @PostMapping(path = "/personal") // Map ONLY POST Requests
    public @ResponseBody String addNewFactory(@RequestParam String name) {
        return "Saved";
    }
}
